### ISSUE TITLE
`knative-serving` goes into error state

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/knative-operators#103]
I just tried to deploy bundle from 1.7/edge

do not think this is always reproducible, but we might wrap somehow the error handler
here is the trace

```
 controller-0: 23:51:46 ERROR juju.worker.caasapplicationprovisioner.runner exited "knative-serving": Operation cannot be fulfilled on pods "knative-serving-0": the object has been modified; please apply your changes to the latest version and try again
unit-knative-serving-0: 23:51:51 ERROR unit.knative-serving/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 132, in <module>
    main(KnativeServingCharm)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/ops/main.py", line 436, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/ops/framework.py", line 866, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 68, in _on_install
    self._apply_and_set_status()
  File "./src/charm.py", line 47, in _apply_and_set_status
    self.resource_handler.apply()
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py", line 206, in apply
    apply_many(self.lightkube_client, resources)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/charmed_kubeflow_chisme/lightkube/batch/_many.py", line 64, in apply_many
    returns[i] = client.apply(
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/client.py", line 424, in apply
    return self.patch(type(obj), name, obj, namespace=namespace,
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/client.py", line 293, in patch
    return self._client.request("patch", res=res, name=name, namespace=namespace, obj=obj,
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/generic_client.py", line 245, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/generic_client.py", line 196, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/generic_client.py", line 190, in raise_for_status
    raise transform_exception(e)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/generic_client.py", line 188, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/httpx/_models.py", line 745, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://10.152.183.1/apis/operator.knative.dev/v1beta1/namespaces/knative-serving/knativeservings/knative-serving?fieldManager=kubeflow'
```

**Comment by NohaIhab** [comment]
this version of `knative-serving` is no longer supported, and we no longer run into this error for the latest supported version `1.16/stable`
